services:
  piqchat-inbox-server:
    image: piqchat/piqchat-inbox-server:latest

    ports:
      - "8080:8080"

    volumes:
      - ./database:/database
      - ./uploads:/uploads

    env_file:
      - .env

    environment:
      - PORT=8080
      - DATABASE_PATH=/database/database.sqlite
      - PARCEL_ATTACHMENTS_UPLOAD_PATH=/uploads/parcel_attachments/

    restart: on-failure
