services:
  piqchat-inbox-server:
    image: piqchat-inbox-server:latest
    
    ports:
      # [HOSTPORT:PIQCHATPORT]
      - "8080:8080"                 # CHANGEME (HOSTPORT)

    # Volumes containing database and user uploads
    volumes:
      # [HOSTPATH:PIQCHATPATH]
      - ./piqchat_db:/db            # CHANGEME (HOSTPATH)
      - ./piqchat_uploads:/uploads  # CHANGEME (HOSTPATH)

    env_file:
      - .env

    restart: on-failure

